//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.26 at 02:37:53 PM CST 
//


package com.linus.xml.jaxb.test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ExportDeclaration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExportDeclaration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterConsignee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsPartiesRelation" type="{http://www.dhl.com/datatypes_global}YesNo" minOccurs="0"/>
 *         &lt;element name="ECCN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SignatureName" type="{http://www.dhl.com/datatypes_global}SignatureName" minOccurs="0"/>
 *         &lt;element name="SignatureTitle" type="{http://www.dhl.com/datatypes_global}SignatureTitle" minOccurs="0"/>
 *         &lt;element name="ExportReason" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExportReasonCode" type="{http://www.dhl.com/datatypes_global}ExportReasonCode" minOccurs="0"/>
 *         &lt;element name="SedNumber" type="{http://www.dhl.com/datatypes_global}SEDNumber" minOccurs="0"/>
 *         &lt;element name="SedNumberType" type="{http://www.dhl.com/datatypes_global}SEDNumberType" minOccurs="0"/>
 *         &lt;element name="MxStateCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InvoiceDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="BillToCompanyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToContanctName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToAddressLine" type="{http://www.dhl.com/datatypes_global}AddressLine" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="BillToCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToPostcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToSuburb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToCountryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToPhoneNumberExtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToFaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillToFederalTaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherCharges1" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="OtherCharges2" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="OtherCharges3" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="DestinationPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TermsOfPayment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PayerGSTVAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SignatureImage" type="{http://www.dhl.com/datatypes_global}SignatureImage" minOccurs="0"/>
 *         &lt;element name="ReceiverReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExporterId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExporterCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PackageMarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherRemarks2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherRemarks3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankINN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankKPP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankOKPO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankOGRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankSettlementAcctNumUSDEUR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankSettlementAcctNumRUR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RUBankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddDeclText1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="300"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AddDeclText2" type="{http://www.dhl.com/datatypes_global}AddDeclText" minOccurs="0"/>
 *         &lt;element name="AddDeclText3" type="{http://www.dhl.com/datatypes_global}AddDeclText" minOccurs="0"/>
 *         &lt;element name="ExportLineItem" type="{http://www.dhl.com/datatypes_global}ExportLineItem" maxOccurs="unbounded"/>
 *         &lt;element name="ShipmentDocument" type="{http://www.dhl.com/datatypes_global}ShipmentDocument" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportDeclaration", propOrder = {
    "interConsignee",
    "isPartiesRelation",
    "eccn",
    "signatureName",
    "signatureTitle",
    "exportReason",
    "exportReasonCode",
    "sedNumber",
    "sedNumberType",
    "mxStateCode",
    "invoiceNumber",
    "invoiceDate",
    "billToCompanyName",
    "billToContanctName",
    "billToAddressLine",
    "billToCity",
    "billToPostcode",
    "billToSuburb",
    "billToState",
    "billToCountryName",
    "billToPhoneNumber",
    "billToPhoneNumberExtn",
    "billToFaxNumber",
    "billToFederalTaxID",
    "remarks",
    "otherCharges1",
    "otherCharges2",
    "otherCharges3",
    "destinationPort",
    "termsOfPayment",
    "payerGSTVAT",
    "signatureImage",
    "receiverReference",
    "exporterId",
    "exporterCode",
    "packageMarks",
    "otherRemarks2",
    "otherRemarks3",
    "ruBankINN",
    "ruBankKPP",
    "ruBankOKPO",
    "ruBankOGRN",
    "ruBankSettlementAcctNumUSDEUR",
    "ruBankSettlementAcctNumRUR",
    "ruBankName",
    "addDeclText1",
    "addDeclText2",
    "addDeclText3",
    "exportLineItem",
    "shipmentDocument"
})
public class ExportDeclaration {

    @XmlElement(name = "InterConsignee")
    protected String interConsignee;
    @XmlElement(name = "IsPartiesRelation")
    @XmlSchemaType(name = "string")
    protected YesNo isPartiesRelation;
    @XmlElement(name = "ECCN")
    protected String eccn;
    @XmlElement(name = "SignatureName")
    protected String signatureName;
    @XmlElement(name = "SignatureTitle")
    protected String signatureTitle;
    @XmlElement(name = "ExportReason")
    protected String exportReason;
    @XmlElement(name = "ExportReasonCode")
    @XmlSchemaType(name = "string")
    protected ExportReasonCode exportReasonCode;
    @XmlElement(name = "SedNumber")
    @XmlSchemaType(name = "string")
    protected SEDNumber sedNumber;
    @XmlElement(name = "SedNumberType")
    @XmlSchemaType(name = "string")
    protected SEDNumberType sedNumberType;
    @XmlElement(name = "MxStateCode")
    protected String mxStateCode;
    @XmlElement(name = "InvoiceNumber", required = true)
    protected String invoiceNumber;
    @XmlElement(name = "InvoiceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "BillToCompanyName")
    protected String billToCompanyName;
    @XmlElement(name = "BillToContanctName")
    protected String billToContanctName;
    @XmlElement(name = "BillToAddressLine")
    protected List<String> billToAddressLine;
    @XmlElement(name = "BillToCity")
    protected String billToCity;
    @XmlElement(name = "BillToPostcode")
    protected String billToPostcode;
    @XmlElement(name = "BillToSuburb")
    protected String billToSuburb;
    @XmlElement(name = "BillToState")
    protected String billToState;
    @XmlElement(name = "BillToCountryName")
    protected String billToCountryName;
    @XmlElement(name = "BillToPhoneNumber")
    protected String billToPhoneNumber;
    @XmlElement(name = "BillToPhoneNumberExtn")
    protected String billToPhoneNumberExtn;
    @XmlElement(name = "BillToFaxNumber")
    protected String billToFaxNumber;
    @XmlElement(name = "BillToFederalTaxID")
    protected String billToFederalTaxID;
    @XmlElement(name = "Remarks")
    protected String remarks;
    @XmlElement(name = "OtherCharges1")
    protected Float otherCharges1;
    @XmlElement(name = "OtherCharges2")
    protected Float otherCharges2;
    @XmlElement(name = "OtherCharges3")
    protected Float otherCharges3;
    @XmlElement(name = "DestinationPort")
    protected String destinationPort;
    @XmlElement(name = "TermsOfPayment")
    protected String termsOfPayment;
    @XmlElement(name = "PayerGSTVAT")
    protected String payerGSTVAT;
    @XmlElement(name = "SignatureImage")
    protected byte[] signatureImage;
    @XmlElement(name = "ReceiverReference")
    protected String receiverReference;
    @XmlElement(name = "ExporterId")
    protected String exporterId;
    @XmlElement(name = "ExporterCode")
    protected String exporterCode;
    @XmlElement(name = "PackageMarks")
    protected String packageMarks;
    @XmlElement(name = "OtherRemarks2")
    protected String otherRemarks2;
    @XmlElement(name = "OtherRemarks3")
    protected String otherRemarks3;
    @XmlElement(name = "RUBankINN")
    protected String ruBankINN;
    @XmlElement(name = "RUBankKPP")
    protected String ruBankKPP;
    @XmlElement(name = "RUBankOKPO")
    protected String ruBankOKPO;
    @XmlElement(name = "RUBankOGRN")
    protected String ruBankOGRN;
    @XmlElement(name = "RUBankSettlementAcctNumUSDEUR")
    protected String ruBankSettlementAcctNumUSDEUR;
    @XmlElement(name = "RUBankSettlementAcctNumRUR")
    protected String ruBankSettlementAcctNumRUR;
    @XmlElement(name = "RUBankName")
    protected String ruBankName;
    @XmlElement(name = "AddDeclText1")
    protected String addDeclText1;
    @XmlElement(name = "AddDeclText2")
    protected String addDeclText2;
    @XmlElement(name = "AddDeclText3")
    protected String addDeclText3;
    @XmlElement(name = "ExportLineItem", required = true)
    protected List<ExportLineItem> exportLineItem;
    @XmlElement(name = "ShipmentDocument")
    protected ShipmentDocument shipmentDocument;

    /**
     * Gets the value of the interConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterConsignee() {
        return interConsignee;
    }

    /**
     * Sets the value of the interConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterConsignee(String value) {
        this.interConsignee = value;
    }

    /**
     * Gets the value of the isPartiesRelation property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getIsPartiesRelation() {
        return isPartiesRelation;
    }

    /**
     * Sets the value of the isPartiesRelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setIsPartiesRelation(YesNo value) {
        this.isPartiesRelation = value;
    }

    /**
     * Gets the value of the eccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECCN() {
        return eccn;
    }

    /**
     * Sets the value of the eccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECCN(String value) {
        this.eccn = value;
    }

    /**
     * Gets the value of the signatureName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureName() {
        return signatureName;
    }

    /**
     * Sets the value of the signatureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureName(String value) {
        this.signatureName = value;
    }

    /**
     * Gets the value of the signatureTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureTitle() {
        return signatureTitle;
    }

    /**
     * Sets the value of the signatureTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureTitle(String value) {
        this.signatureTitle = value;
    }

    /**
     * Gets the value of the exportReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportReason() {
        return exportReason;
    }

    /**
     * Sets the value of the exportReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportReason(String value) {
        this.exportReason = value;
    }

    /**
     * Gets the value of the exportReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link ExportReasonCode }
     *     
     */
    public ExportReasonCode getExportReasonCode() {
        return exportReasonCode;
    }

    /**
     * Sets the value of the exportReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportReasonCode }
     *     
     */
    public void setExportReasonCode(ExportReasonCode value) {
        this.exportReasonCode = value;
    }

    /**
     * Gets the value of the sedNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SEDNumber }
     *     
     */
    public SEDNumber getSedNumber() {
        return sedNumber;
    }

    /**
     * Sets the value of the sedNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEDNumber }
     *     
     */
    public void setSedNumber(SEDNumber value) {
        this.sedNumber = value;
    }

    /**
     * Gets the value of the sedNumberType property.
     * 
     * @return
     *     possible object is
     *     {@link SEDNumberType }
     *     
     */
    public SEDNumberType getSedNumberType() {
        return sedNumberType;
    }

    /**
     * Sets the value of the sedNumberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEDNumberType }
     *     
     */
    public void setSedNumberType(SEDNumberType value) {
        this.sedNumberType = value;
    }

    /**
     * Gets the value of the mxStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMxStateCode() {
        return mxStateCode;
    }

    /**
     * Sets the value of the mxStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMxStateCode(String value) {
        this.mxStateCode = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the billToCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToCompanyName() {
        return billToCompanyName;
    }

    /**
     * Sets the value of the billToCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToCompanyName(String value) {
        this.billToCompanyName = value;
    }

    /**
     * Gets the value of the billToContanctName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToContanctName() {
        return billToContanctName;
    }

    /**
     * Sets the value of the billToContanctName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToContanctName(String value) {
        this.billToContanctName = value;
    }

    /**
     * Gets the value of the billToAddressLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billToAddressLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillToAddressLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBillToAddressLine() {
        if (billToAddressLine == null) {
            billToAddressLine = new ArrayList<String>();
        }
        return this.billToAddressLine;
    }

    /**
     * Gets the value of the billToCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToCity() {
        return billToCity;
    }

    /**
     * Sets the value of the billToCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToCity(String value) {
        this.billToCity = value;
    }

    /**
     * Gets the value of the billToPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToPostcode() {
        return billToPostcode;
    }

    /**
     * Sets the value of the billToPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToPostcode(String value) {
        this.billToPostcode = value;
    }

    /**
     * Gets the value of the billToSuburb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToSuburb() {
        return billToSuburb;
    }

    /**
     * Sets the value of the billToSuburb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToSuburb(String value) {
        this.billToSuburb = value;
    }

    /**
     * Gets the value of the billToState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToState() {
        return billToState;
    }

    /**
     * Sets the value of the billToState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToState(String value) {
        this.billToState = value;
    }

    /**
     * Gets the value of the billToCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToCountryName() {
        return billToCountryName;
    }

    /**
     * Sets the value of the billToCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToCountryName(String value) {
        this.billToCountryName = value;
    }

    /**
     * Gets the value of the billToPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToPhoneNumber() {
        return billToPhoneNumber;
    }

    /**
     * Sets the value of the billToPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToPhoneNumber(String value) {
        this.billToPhoneNumber = value;
    }

    /**
     * Gets the value of the billToPhoneNumberExtn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToPhoneNumberExtn() {
        return billToPhoneNumberExtn;
    }

    /**
     * Sets the value of the billToPhoneNumberExtn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToPhoneNumberExtn(String value) {
        this.billToPhoneNumberExtn = value;
    }

    /**
     * Gets the value of the billToFaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToFaxNumber() {
        return billToFaxNumber;
    }

    /**
     * Sets the value of the billToFaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToFaxNumber(String value) {
        this.billToFaxNumber = value;
    }

    /**
     * Gets the value of the billToFederalTaxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToFederalTaxID() {
        return billToFederalTaxID;
    }

    /**
     * Sets the value of the billToFederalTaxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToFederalTaxID(String value) {
        this.billToFederalTaxID = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the otherCharges1 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOtherCharges1() {
        return otherCharges1;
    }

    /**
     * Sets the value of the otherCharges1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOtherCharges1(Float value) {
        this.otherCharges1 = value;
    }

    /**
     * Gets the value of the otherCharges2 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOtherCharges2() {
        return otherCharges2;
    }

    /**
     * Sets the value of the otherCharges2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOtherCharges2(Float value) {
        this.otherCharges2 = value;
    }

    /**
     * Gets the value of the otherCharges3 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOtherCharges3() {
        return otherCharges3;
    }

    /**
     * Sets the value of the otherCharges3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOtherCharges3(Float value) {
        this.otherCharges3 = value;
    }

    /**
     * Gets the value of the destinationPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * Sets the value of the destinationPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationPort(String value) {
        this.destinationPort = value;
    }

    /**
     * Gets the value of the termsOfPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsOfPayment() {
        return termsOfPayment;
    }

    /**
     * Sets the value of the termsOfPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsOfPayment(String value) {
        this.termsOfPayment = value;
    }

    /**
     * Gets the value of the payerGSTVAT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerGSTVAT() {
        return payerGSTVAT;
    }

    /**
     * Sets the value of the payerGSTVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerGSTVAT(String value) {
        this.payerGSTVAT = value;
    }

    /**
     * Gets the value of the signatureImage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSignatureImage() {
        return signatureImage;
    }

    /**
     * Sets the value of the signatureImage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSignatureImage(byte[] value) {
        this.signatureImage = value;
    }

    /**
     * Gets the value of the receiverReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverReference() {
        return receiverReference;
    }

    /**
     * Sets the value of the receiverReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverReference(String value) {
        this.receiverReference = value;
    }

    /**
     * Gets the value of the exporterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterId() {
        return exporterId;
    }

    /**
     * Sets the value of the exporterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterId(String value) {
        this.exporterId = value;
    }

    /**
     * Gets the value of the exporterCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterCode() {
        return exporterCode;
    }

    /**
     * Sets the value of the exporterCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterCode(String value) {
        this.exporterCode = value;
    }

    /**
     * Gets the value of the packageMarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageMarks() {
        return packageMarks;
    }

    /**
     * Sets the value of the packageMarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageMarks(String value) {
        this.packageMarks = value;
    }

    /**
     * Gets the value of the otherRemarks2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRemarks2() {
        return otherRemarks2;
    }

    /**
     * Sets the value of the otherRemarks2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRemarks2(String value) {
        this.otherRemarks2 = value;
    }

    /**
     * Gets the value of the otherRemarks3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRemarks3() {
        return otherRemarks3;
    }

    /**
     * Sets the value of the otherRemarks3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRemarks3(String value) {
        this.otherRemarks3 = value;
    }

    /**
     * Gets the value of the ruBankINN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankINN() {
        return ruBankINN;
    }

    /**
     * Sets the value of the ruBankINN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankINN(String value) {
        this.ruBankINN = value;
    }

    /**
     * Gets the value of the ruBankKPP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankKPP() {
        return ruBankKPP;
    }

    /**
     * Sets the value of the ruBankKPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankKPP(String value) {
        this.ruBankKPP = value;
    }

    /**
     * Gets the value of the ruBankOKPO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankOKPO() {
        return ruBankOKPO;
    }

    /**
     * Sets the value of the ruBankOKPO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankOKPO(String value) {
        this.ruBankOKPO = value;
    }

    /**
     * Gets the value of the ruBankOGRN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankOGRN() {
        return ruBankOGRN;
    }

    /**
     * Sets the value of the ruBankOGRN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankOGRN(String value) {
        this.ruBankOGRN = value;
    }

    /**
     * Gets the value of the ruBankSettlementAcctNumUSDEUR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankSettlementAcctNumUSDEUR() {
        return ruBankSettlementAcctNumUSDEUR;
    }

    /**
     * Sets the value of the ruBankSettlementAcctNumUSDEUR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankSettlementAcctNumUSDEUR(String value) {
        this.ruBankSettlementAcctNumUSDEUR = value;
    }

    /**
     * Gets the value of the ruBankSettlementAcctNumRUR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankSettlementAcctNumRUR() {
        return ruBankSettlementAcctNumRUR;
    }

    /**
     * Sets the value of the ruBankSettlementAcctNumRUR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankSettlementAcctNumRUR(String value) {
        this.ruBankSettlementAcctNumRUR = value;
    }

    /**
     * Gets the value of the ruBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUBankName() {
        return ruBankName;
    }

    /**
     * Sets the value of the ruBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUBankName(String value) {
        this.ruBankName = value;
    }

    /**
     * Gets the value of the addDeclText1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddDeclText1() {
        return addDeclText1;
    }

    /**
     * Sets the value of the addDeclText1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddDeclText1(String value) {
        this.addDeclText1 = value;
    }

    /**
     * Gets the value of the addDeclText2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddDeclText2() {
        return addDeclText2;
    }

    /**
     * Sets the value of the addDeclText2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddDeclText2(String value) {
        this.addDeclText2 = value;
    }

    /**
     * Gets the value of the addDeclText3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddDeclText3() {
        return addDeclText3;
    }

    /**
     * Sets the value of the addDeclText3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddDeclText3(String value) {
        this.addDeclText3 = value;
    }

    /**
     * Gets the value of the exportLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exportLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExportLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExportLineItem }
     * 
     * 
     */
    public List<ExportLineItem> getExportLineItem() {
        if (exportLineItem == null) {
            exportLineItem = new ArrayList<ExportLineItem>();
        }
        return this.exportLineItem;
    }

    /**
     * Gets the value of the shipmentDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentDocument }
     *     
     */
    public ShipmentDocument getShipmentDocument() {
        return shipmentDocument;
    }

    /**
     * Sets the value of the shipmentDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentDocument }
     *     
     */
    public void setShipmentDocument(ShipmentDocument value) {
        this.shipmentDocument = value;
    }

}
